/*
 * MarcoDiametro.java
 *
 * TODO: Descripcion
 *
 * Creado en 31 de diciembre de 2006, 12:11
 *
 * Copyright (C) 31 de diciembre de 2006, Protactino
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */


package es.atareao.ferraplan.gui;
//
//********************************IMPORTACIONES*********************************
//
import es.atareao.alejandria.gui.ErrorDialog;
import es.atareao.alejandria.val.gui.GuiNotEmptyValidator;
import es.atareao.ferraplan.lib.Fabricante;
import es.atareao.ferraplan.lib.Pais;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFrame;


/**
 *
 * @author  Protactino
 */
public class DialogFabricante extends javax.swing.JDialog {
    //
    //********************************CONSTANTES********************************
    //
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    //
    public final static int OP_ADD=0;
    public final static int OP_EDIT=1;
    public final static int OP_DELETE=2;
    public final static int OP_VIEW=3;
    //
    //******************************CONSTRUCTORES*******************************
    //
    /**
     * Creates new form MarcoEmpresa
     * @param padre 
     * @param operacion 
     * @param empresa 
     * @throws java.sql.SQLException 
     */
    public DialogFabricante(JFrame padre,int operacion,Fabricante fabricante) throws SQLException {
        super(padre,true);
        initComponents();
        this.setSize(410,245);
        this.setLocationRelativeTo(null);
        this.setOperacion(operacion);
        //
        switch (operacion){
            case OP_ADD:
                this.setTitle("Añadir Fabricante");
                break;
            case OP_EDIT:
                this.setTitle("Editar Fabricante");
                break;
            case OP_DELETE:
                this.setTitle("Borrar Fabricante");
                this.doNotEditable();
                break;
            case OP_VIEW:
                this.setTitle("Consultar Fabricante");
                this.doNotEditable();
                break;
        }
        //
        this.setFabricante(fabricante);
        Pais pais=new Pais(fabricante.getConector());
        this.jPais.setElements(pais.findAll());
        this.jNombre.requestFocus();
    }
    
    public DialogFabricante(int operacion,Fabricante fabricante) throws SQLException{
        this(new JFrame(),operacion,fabricante);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jIdentificacion = new es.atareao.alejandria.gui.JNumericField();
        jPais = new es.atareao.queensboro.gui.JWrapperComboBox();
        jLabel4 = new javax.swing.JLabel();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Diámetros");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Razón Social:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel3.setText("País:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jNombre.setInputVerifier(new GuiNotEmptyValidator(this,jNombre));
        jPanel1.add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 260, 30));
        jPanel1.add(jIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, 30));
        jPanel1.add(jPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, 30));

        jLabel4.setText("Identificación:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 140));

        jAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_ok.png"))); // NOI18N
        jAceptar.setBorderPainted(false);
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 50));

        jCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_cancel.png"))); // NOI18N
        jCancelar.setBorderPainted(false);
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDiametroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDiametroPropertyChange

    }//GEN-LAST:event_jDiametroPropertyChange
    
    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
// TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jCancelarActionPerformed
    
    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
// TODO add your handling code here:
        doClose(RET_OK);
    }//GEN-LAST:event_jAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jCancelar;
    private es.atareao.alejandria.gui.JNumericField jIdentificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNombre;
    private es.atareao.queensboro.gui.JWrapperComboBox jPais;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    //
    // *********************************CAMPOS*********************************
    //
    private int _returnStatus = RET_CANCEL;
    private int _operacion;
    private Fabricante _fabricante;
    //
    //********************************METODOS***********************************
    //
    private boolean valida(JComponent main){
        boolean ans=true;
        InputVerifier iv=main.getInputVerifier();
        if(iv!=null){
            if(!iv.verify(main)){
                ans=false;
            }
        }
        for(Component c:main.getComponents()){
            if(c instanceof JComponent){
                if(!valida(((JComponent)c))){
                    ans=false;
                }
            }
        }
        return ans;
    }
    private boolean valida(){
        return this.valida(this.jPanel1);
    }
    //
    //**************************METODOS AUXILIARES******************************
    //
    private void doClose(int retStatus) {
        if(retStatus==RET_OK){
            if(valida()){
                try {
                    if(this.fromDialog().validate()){
                        this.setFabricante(this.fromDialog());
                        this.setReturnStatus(retStatus);
                        setVisible(false);
                        dispose();
                    }
                } catch (Exception ex) {
                     ErrorDialog.manejaError(ex,false);
                }
            }
        }else{
            this.setReturnStatus(retStatus);
            setVisible(false);
            dispose();
        }
    }    

    private void doNotEditable(){
        this.jNombre.setEditable(false);
        this.jIdentificacion.setEditable(false);
        this.jPais.setEditable(false);
        //
        this.jNombre.setBackground(java.awt.SystemColor.info);
        this.jIdentificacion.setBackground(java.awt.SystemColor.info);
        this.jPais.setBackground(java.awt.SystemColor.info);
    }
    
    private Fabricante fromDialog(){
        String nombre=this.jNombre.getText();
        String numero=this.jIdentificacion.getText();
        String pais=this.jPais.getSelectedId();
        this.getFabricante().setValue("nombre", nombre);
        this.getFabricante().setValue("numero",numero);
        this.getFabricante().setValue("pais_id", pais);
        return this.getFabricante();
    }
    private void toDialog(Fabricante fabricante){
        String nombre=fabricante.getValue("nombre");
        String numero=fabricante.getValue("numero");
        String pais=fabricante.getValue("pais_id");
        this.jNombre.setText(nombre);
        this.jIdentificacion.setText(numero);
        this.jPais.setSelectedId(pais);
    } 
    
    //
    //**************************METODOS DE ACCESO*******************************
    //
    
    public int getReturnStatus() {
        return _returnStatus;
    }
    
    public void setReturnStatus(int returnStatus) {
        this._returnStatus = returnStatus;
    }
    
    public int getOperacion() {
        return _operacion;
    }

    public void setOperacion(int operacion) {
        this._operacion = operacion;
    }

    /**
     * @return the _fabricante
     */
    public Fabricante getFabricante() {
        return _fabricante;
    }

    /**
     * @param fabricante the _fabricante to set
     */
    public void setFabricante(Fabricante fabricante) {
        this._fabricante = fabricante;
        this.toDialog(fabricante);
    }
    
}
