/*
 * MarcoDiametros.java
 *
 * Created on 7 de octubre de 2007, 13:18
 */

package es.atareao.ferraplan.gui;

//
//********************************IMPORTACIONES*********************************
//
import es.atareao.alejandria.gui.ErrorDialog;
import es.atareao.queensboro.db.Conector;
import es.atareao.ferraplan.lib.Diametro;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author  Propietario
 */
public class DialogDiametros extends javax.swing.JFrame {
    //
    //********************************CONSTANTES********************************
    //
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    //
    public final static int OP_ADD=0;
    public final static int OP_EDIT=1;
    public final static int OP_DELETE=2;
    public final static int OP_VIEW=3;
    //
    //******************************CONSTRUCTORES*******************************
    //
    
    /** Creates new form MarcoDiametros */
    public DialogDiametros(Conector conector) {
        initComponents();
        this.setSize(410,430);
        this.setLocationRelativeTo(null);
        try {
            this.setDiametro(new Diametro(conector));
        } catch (SQLException ex) {
            ErrorDialog.manejaError(ex,false);
        }
        this.refresca();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemAñadir = new javax.swing.JMenuItem();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jMenuItemConsultar = new javax.swing.JMenuItem();
        jMenuItemBorrar = new javax.swing.JMenuItem();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenuItemAñadir.setText("Añadir");
        jMenuItemAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemAñadir);

        jMenuItemEditar.setText("Editar");
        jMenuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemEditar);

        jMenuItemConsultar.setText("Consultar");
        jMenuItemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemConsultar);

        jMenuItemBorrar.setText("Borrar");
        jMenuItemBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemBorrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Diámetros");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_ok.png"))); // NOI18N
        jAceptar.setBorderPainted(false);
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 50, 50));

        jCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_cancel.png"))); // NOI18N
        jCancelar.setBorderPainted(false);
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 50, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarActionPerformed
        this.operaciones(OP_DELETE);
    }//GEN-LAST:event_jMenuItemBorrarActionPerformed

    private void jMenuItemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarActionPerformed
        this.operaciones(OP_VIEW);
    }//GEN-LAST:event_jMenuItemConsultarActionPerformed

    private void jMenuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarActionPerformed
        this.operaciones(OP_EDIT);
    }//GEN-LAST:event_jMenuItemEditarActionPerformed

    private void jMenuItemAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirActionPerformed
        this.operaciones(OP_ADD);
    }//GEN-LAST:event_jMenuItemAñadirActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
// TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
// TODO add your handling code here:
        doClose(RET_OK);
    }//GEN-LAST:event_jAceptarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JMenuItem jMenuItemAñadir;
    private javax.swing.JMenuItem jMenuItemBorrar;
    private javax.swing.JMenuItem jMenuItemConsultar;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    //
    // *********************************CAMPOS*********************************
    //
    private int _returnStatus = RET_CANCEL;
    private int _operacion;
    private Diametro _diametro;
    //
    //********************************METODOS***********************************
    //
    
    //
    //**************************METODOS AUXILIARES******************************
    //
    private void operaciones(int operacion){
        DialogDiametro md;
        String selectedId="";
        int selectedRow=this.jTable1.getSelectedRow();
        if(selectedRow>-1){
            selectedId=(String)this.jTable1.getValueAt(selectedRow,0);
        }
        try{
            switch(operacion){
                case OP_ADD:
                    md=new DialogDiametro(this,operacion,this.getDiametro());
                    md.setVisible(true);
                    if(md.getReturnStatus()==DialogDiametro.RET_OK){
                        if(md.getDiametro().insert()){
                            if(((String)this.jTable1.getValueAt(0,0)).equals("")){
                                this.jTable1.setValueAt(md.getDiametro().getValue("orden"),0,0);
                                this.jTable1.setValueAt(md.getDiametro().getLastInsertId(),0,1);
                                this.jTable1.setValueAt(md.getDiametro(),0,2);
                                this.jTable1.setValueAt(md.getDiametro().getValue("peso"),0,3);
                            }else{
                                //Diametro diametro=md.getDiametro().getLastInserted();
                                Diametro diametro=md.getDiametro();
                                Object[] fila={diametro.getValue("orden"),diametro.getId(),diametro,diametro.getValue("peso")};
                                ((DefaultTableModel)this.jTable1.getModel()).addRow(fila);
                            }
                        }
                    }
                    break;
                case OP_EDIT:
                    if(selectedRow>-1){
                        Diametro diametro=(Diametro)this.jTable1.getValueAt(selectedRow,2);
                        md=new DialogDiametro(this,operacion,diametro);
                        md.setVisible(true);
                        if(md.getReturnStatus()==DialogDiametro.RET_OK){
                            if(md.getDiametro().update()){
                                ((DefaultTableModel)this.jTable1.getModel()).setValueAt(md.getDiametro().getValue("orden"),selectedRow,0);
                                ((DefaultTableModel)this.jTable1.getModel()).setValueAt(selectedId,selectedRow,1);
                                ((DefaultTableModel)this.jTable1.getModel()).setValueAt(md.getDiametro(),selectedRow,2);
                                ((DefaultTableModel)this.jTable1.getModel()).setValueAt(md.getDiametro().getValue("PESO"),selectedRow,3);
                            }
                        }
                    }
                    break;
                case OP_VIEW:
                    if(selectedRow>-1){
                        Diametro diametro=(Diametro)this.jTable1.getValueAt(selectedRow,2);
                        md=new DialogDiametro(this,operacion,diametro);
                        md.setVisible(true);
                        break;
                    }
                case OP_DELETE:
                    if(selectedRow>-1){
                        this.getDiametro().setId(selectedId);
                        if(this.getDiametro().delete()){
                            if(selectedRow==0){
                                this.jTable1.setValueAt("",0,0);
                                this.jTable1.setValueAt("",0,1);
                                this.jTable1.setValueAt("",0,2);
                                this.jTable1.setValueAt("",0,3);
                            }else{
                                ((DefaultTableModel)this.jTable1.getModel()).removeRow(selectedRow);
                            }
                        }
                    }
                    break;
            }
        }catch(SQLException ex){
            ErrorDialog.manejaError(ex,false);
        }
    }
    private void refresca(){
        this.jTable1.setModel(new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return false;
            }
        });
        String[] columnNamesDiametro={"orden","id","Diametro","Peso"};
        ((DefaultTableModel)this.jTable1.getModel()).setColumnIdentifiers(columnNamesDiametro);
        this.setColumnWidth(0,0);
        this.setColumnWidth(1,0);
        try {
            for(Diametro this_diametro:this.getDiametro().find("orden")){
                Object[] fila={this_diametro.getValue("orden"),this_diametro.getValue("id"),this_diametro,this_diametro.getValue("peso")};
                ((DefaultTableModel)this.jTable1.getModel()).addRow(fila);
            }
            if(this.jTable1.getRowCount()==0){
                Object[] fila={"","","",""};
                ((DefaultTableModel)this.jTable1.getModel()).addRow(fila);
            }
        } catch (SQLException ex) {
            ErrorDialog.manejaError(ex,false);
        }
        this.jTable1.setUI(new DragDropRowTableUIOrdered());
    }
    private void doClose(int retStatus) {
        dispose();
    }   
    private void setColumnWidth(int column,int width){
        this.jTable1.getColumnModel().getColumn(column).setPreferredWidth(width);
        this.jTable1.getColumnModel().getColumn(column).setMinWidth(width);
        this.jTable1.getColumnModel().getColumn(column).setMaxWidth(width);
        this.jTable1.getColumnModel().getColumn(column).setWidth(width);
    }    

    public Diametro getDiametro() {
        return _diametro;
    }

    public void setDiametro(Diametro diametro) {
        this._diametro = diametro;
    }
    
}
