/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformeDialog.java
 *
 * Created on 28-feb-2010, 11:29:28
 */

package es.atareao.ferraplan.gui;

import es.atareao.alejandria.lib.DateUtils;
import java.util.Date;

/**
 *
 * @author atareao
 */
public class DialogReport extends javax.swing.JDialog {
    //
    //********************************CONSTANTES********************************
    //
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    //
    //
    //******************************CONSTRUCTORES*******************************
    //
    /** Creates new form InformeDialog */
    public DialogReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(410, 190);
        this.setLocationRelativeTo(null);
        this.jDesde.setDate(DateUtils.addMonths(DateUtils.Ahora(),-1));
        this.jHasta.setDate(DateUtils.Ahora());
    }
    private void doClose(int retStatus) {
        if(retStatus==RET_OK){
            this.setDesde(this.jDesde.getDate());
            this.setHasta(this.jHasta.getDate());
        }
        this.setReturnStatus(retStatus);
        setVisible(false);
        dispose();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesde = new es.atareao.alejandria.gui.JDateChooser();
        jHasta = new es.atareao.alejandria.gui.JDateChooser();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Planillas Pedidas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Desde:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        jLabel2.setText("Hasta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));
        jPanel1.add(jDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 30));
        jPanel1.add(jHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 90));

        jAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_ok.png"))); // NOI18N
        jAceptar.setBorderPainted(false);
        jAceptar.setPreferredSize(new java.awt.Dimension(50, 50));
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_cancel.png"))); // NOI18N
        jCancelar.setBorderPainted(false);
        jCancelar.setPreferredSize(new java.awt.Dimension(50, 50));
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        this.doClose(RET_OK);
    }//GEN-LAST:event_jAceptarActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        this.doClose(RET_CANCEL);
    }//GEN-LAST:event_jCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jCancelar;
    private es.atareao.alejandria.gui.JDateChooser jDesde;
    private es.atareao.alejandria.gui.JDateChooser jHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private Date _desde;
    private Date _hasta;
    private int _returnStatus = RET_CANCEL;

    /**
     * @return the _desde
     */
    public Date getDesde() {
        return _desde;
    }

    /**
     * @param desde the _desde to set
     */
    public void setDesde(Date desde) {
        this._desde = desde;
    }

    /**
     * @return the _hasta
     */
    public Date getHasta() {
        return _hasta;
    }

    /**
     * @param hasta the _hasta to set
     */
    public void setHasta(Date hasta) {
        this._hasta = hasta;
    }

    /**
     * @return the _returnStatus
     */
    public int getReturnStatus() {
        return _returnStatus;
    }

    /**
     * @param returnStatus the _returnStatus to set
     */
    public void setReturnStatus(int returnStatus) {
        this._returnStatus = returnStatus;
    }
}
